name: Auto Assign Assignees and Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor == 'limhizy15'
        run: echo REVIEWERS="appear, uussong" >> $GITHUB_ENV
      - if: github.actor == 'uussong'
        run: echo REVIEWERS="appear, limhizy15" >> $GITHUB_ENV
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}
